"""Layer 5 — claim/debit packet drafting.

Builds a STRUCTURED packet per discrepancy with every number copied from the case
record (never recomputed by a model). An optional short cover note is generated by
Haiku using ONLY facts already in the packet — it must introduce no new number. A
deterministic template is used as a fallback so the run never depends on the model.
"""

from __future__ import annotations

import re

from anthropic import Anthropic

# Swappable constant — used only for the optional human-readable cover note.
COVER_NOTE_MODEL = "claude-haiku-4-5-20251001"

# packet_type + claim_ref prefix per action.
_ACTION_META = {
    "draft_carrier_freight_claim": ("carrier_freight_claim", "CLAIM"),
    "draft_supplier_debit": ("supplier_debit", "DEBIT"),
    "draft_carrier_loss_claim": ("carrier_loss_claim", "CLAIM"),
    "flag_for_correction": ("correction_flag", "FLAG"),
}


def claim_ref_for(discrepancy: dict, action: str, counterparty_id: str) -> str:
    _, prefix = _ACTION_META.get(action, ("packet", "PKT"))
    return f"{prefix}-{counterparty_id}-{discrepancy['discrepancy_id']}"


def build_packet(discrepancy: dict, case: dict, refs: dict, action: str, routing: str,
                 *, cover_note: bool = True, client: Anthropic | None = None) -> dict:
    """Build the structured packet. All numbers come from the record, never a model."""
    cls = discrepancy["classification"]
    po_line = case["po_line"]
    liable_party = cls["liable_party"]

    if liable_party == "carrier":
        counterparty = {"role": "carrier", "id": refs["carrier_scac"]}
    elif liable_party == "supplier":
        counterparty = {"role": "supplier", "id": refs["supplier_id"]}
    else:
        counterparty = {"role": liable_party, "id": None}

    packet_type, _ = _ACTION_META.get(action, ("packet", "PKT"))
    claim_ref = claim_ref_for(discrepancy, action, counterparty["id"] or "NA")
    status = "auto_filed" if routing == "auto" else "drafted_held_for_human"

    packet = {
        "claim_ref": claim_ref,
        "packet_type": packet_type,
        "action": action,
        "routing": routing,
        "status": status,
        "held_for_human": routing == "escalate",
        "claimant": refs["claimant"],
        "counterparty": counterparty,
        "references": {
            "po_number": po_line["po_number"],
            "bol_number": refs["bol_number"],
            "asn_number": refs["asn_number"],
        },
        "sku": po_line["sku"],
        "qty": discrepancy["qty"],
        "value_usd": discrepancy["value_usd"],
        "currency": po_line["currency"],
        "liable_party": liable_party,
        "cause": cls["cause"],
        "confidence": cls["confidence"],
        "evidence_cited": list(cls["evidence_cited"]),
    }

    text, source = _make_cover_note(packet, use_llm=cover_note, client=client)
    packet["cover_note"] = text
    packet["cover_note_source"] = source
    return packet


# --------------------------------------------------------------------------- #
# cover note (optional LLM; deterministic fallback)
# --------------------------------------------------------------------------- #
def _template_note(packet: dict) -> str:
    cp = packet["counterparty"]
    verb = "freight claim" if packet["packet_type"].startswith("carrier") else "debit"
    return (
        f"{packet['claimant']} is filing a {verb} against {cp['role']} {cp['id']} for "
        f"{packet['qty']} cases of {packet['sku']} valued at ${packet['value_usd']} under "
        f"PO {packet['references']['po_number']} / BOL {packet['references']['bol_number']}, "
        f"attributed to {packet['cause']}."
    )


def _make_cover_note(packet: dict, *, use_llm: bool, client: Anthropic | None) -> tuple[str, str]:
    """Return (note_text, source). Falls back to a deterministic template on any failure."""
    if not use_llm:
        return _template_note(packet), "template"

    facts = {
        "claimant": packet["claimant"],
        "counterparty": packet["counterparty"],
        "po_number": packet["references"]["po_number"],
        "bol_number": packet["references"]["bol_number"],
        "sku": packet["sku"],
        "qty": packet["qty"],
        "value_usd": packet["value_usd"],
        "cause": packet["cause"],
        "liable_party": packet["liable_party"],
        "packet_type": packet["packet_type"],
    }
    prompt = (
        "Write a 1-2 sentence professional cover note for the freight claim / supplier "
        "debit described by these structured facts. Use ONLY these facts. Do NOT introduce "
        "any number, quantity, or dollar amount that is not present below, and state figures "
        "exactly as given. No greeting, no signature, plain text only.\n\n"
        f"{facts}"
    )
    try:
        client = client or Anthropic()
        resp = client.messages.create(
            model=COVER_NOTE_MODEL,
            max_tokens=200,
            messages=[{"role": "user", "content": prompt}],
        )
        text = "".join(b.text for b in resp.content if getattr(b, "type", None) == "text").strip()
        if not text:
            return _template_note(packet), "template"
        return text, COVER_NOTE_MODEL
    except Exception:
        return _template_note(packet), "template"


# --------------------------------------------------------------------------- #
# number-safety check (used by the verifier)
# --------------------------------------------------------------------------- #
def _number_tokens(text: str) -> set[str]:
    """Digit-runs in text, normalized (commas/decimals stripped). e.g. '$1,000.00' -> '1000'."""
    tokens = set()
    for m in re.findall(r"\d[\d,]*(?:\.\d+)?", text):
        norm = m.replace(",", "")
        if "." in norm:
            norm = norm.split(".")[0]  # drop fractional part (e.g. 1000.00 -> 1000)
        tokens.add(norm.lstrip("0") or "0")
    return tokens


def cover_note_invents_numbers(packet: dict) -> list[str]:
    """Return any numeric figure in the cover note that is NOT present in the packet.

    Empty list == clean (no invented numbers).
    """
    import json as _json
    # Everything in the packet EXCEPT the cover note itself is the allowed source.
    allowed_src = {k: v for k, v in packet.items() if k not in ("cover_note", "cover_note_source")}
    allowed = _number_tokens(_json.dumps(allowed_src))
    note_numbers = _number_tokens(packet.get("cover_note", ""))
    return sorted(n for n in note_numbers if n not in allowed)
